USE fitness
GO


CREATE TRIGGER PURCHASES_AFTER_INSERT
ON PURCHASES 
AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;

	if (select quantity from PRODUCTS where  ID = (SELECT PRODUCTID FROM INSERTED))< (select quantity from inserted)
	delete from PURCHASES where ID=(select ID from inserted) 
	
	else
	BEGIN
	UPDATE PRODUCTS
	SET QUANTITY = QUANTITY-(SELECT QUANTITY FROM INSERTED)
	WHERE ID = (SELECT PRODUCTID FROM INSERTED);

	UPDATE CLIENTS
	SET TOTALPURCHASEVALUE = TOTALPURCHASEVALUE + (SELECT PRICE FROM PRODUCTS WHERE ID = (SELECT PRODUCTID FROM INSERTED)) * (SELECT QUANTITY FROM INSERTED)
	WHERE ID = (SELECT CLIENTID FROM INSERTED)

	UPDATE PURCHASES
	SET PRICE= (select price from PRODUCTS where ID=(select productid from inserted))*(select quantity from inserted)
	where id=(select id from inserted)
	END

END
GO




CREATE TRIGGER  SUBSCRIPTIONS_AFTER_INSERT
ON SUBSCRIPTIONS
AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE SUBSCRIPTIONS
	SET EXPIRATIONDATE = (SELECT DATEADD(DAY, (SELECT DURATION FROM SUBSCRIPTIONTYPES WHERE id = (SELECT TYPEid FROM INSERTED)), GETDATE()))
	WHERE ID = (SELECT ID FROM INSERTED);

	UPDATE CLIENTS
	SET TOTALPURCHASEVALUE = TOTALPURCHASEVALUE + (SELECT PRICE FROM SUBSCRIPTIONTYPES WHERE id= (SELECT TYPEid FROM INSERTED))
	WHERE ID = (SELECT CLIENTID FROM INSERTED)

END
GO

CREATE TRIGGER INVOICES_AFTER_INSERT
ON INVOICES
AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE invoices
	set price = (select price from PRODUCTS where ID=(select productid from inserted))*(select quantity from inserted)
	where id=(select id from inserted)

END
GO

